[package]
name = "laskutys"
version = "1.0.0"
entrypoint = "src/lib.typ"
authors = ["Jiahao Li"]
description = "A template for making invoices matching Finnish requirements (VH/3634/00.01.00/2023)."
repository = "https://github.com/TheJiahao/typst-finnish-invoice"
keywords = ["invoice", "finnish", "banking", "accounting"]
compiler = "0.13.1"
license = "MIT"
categories = ["office"]
disciplines = ["business"]
exclude = ["tests/**", ".vscode/**", "rust_tools/target/**", ".github/**"]

[template]
path = "template"
entrypoint = "template/main.typ"
thumbnail = "docs/images/thumbnail.png"

[tool.packager]
paths = ["src", "template", "docs", "rust_tools/rust_tools.wasm"]
