name: Setup
description: Set up Rust

runs:
  using: composite
  steps:
    - name: Setup Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        components: clippy, rustfmt
        cache-workspaces: rust_tools

    - name: Install Just
      uses: baptiste0928/cargo-install@v3
      with:
        crate: just

    - name: Add WASM target
      run: rustup target add wasm32-unknown-unknown
      shell: bash
