name: Setup
description: Set up Rust

runs:
  using: composite
  steps:
    - name: Cache Rust dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Install Just
      uses: baptiste0928/cargo-install@v3
      with:
        crate: just

    - name: Add WASM target
      run: rustup target add wasm32-unknown-unknown
      shell: bash
