name: Setup
description: Set up Rust

runs:
  using: composite
  steps:
    - name: Cache Rust dependencies
      uses: Swatinem/rust-cache@v2
      with:
        workspaces: rust_tools

    - name: Install Just
      uses: baptiste0928/cargo-install@v3
      with:
        crate: just

    - name: Add WASM target
      run: rustup target add wasm32-unknown-unknown
      shell: bash
