[conf]
default-lang = "en"

[lang.en]
invoice = "Invoice"
purchaser = "Recipient"
item = "Item"
quantity = "Qty"
vat = "VAT"
unit_price = "Unit price"
total = "Total"
total_with_tax = "Total incl. VAT"
seller = "Seller"
price_without_vat = "Price without VAT"
price_with_vat = "Price with VAT"
due_date = "Due date"
beneficiary = "Beneficiary"
reference_number = "Reference number"
to_pay = "To pay"

[lang.fi]
invoice = "Lasku"
purchaser = "Vastaanottaja"
item = "Tuote"
quantity = "Määrä"
vat = "ALV"
unit_price = "à-hinta"
total = "Yhteensä"
total_with_tax = "Yhteensä sis. ALV"
seller = "Myyjä"
price_without_vat = "Veroton hinta"
price_with_vat = "Verollinen hinta"
due_date = "Eräpäivä"
beneficiary = "Saaja"
reference_number = "Viitenumero"
to_pay = "Maksettava"

[lang.sv]
invoice = "Faktura"
purchaser = "Köpare"
item = "Produkt"
quantity = "Antal"
vat = "Moms"
unit_price = "à-pris"
total = "Total"
total_with_tax = "Total inkl. moms"
seller = "Säljare"
price_without_vat = "Pris utan moms"
price_with_vat = "Pris med moms"
due_date = "Förfallodag"
beneficiary = "Mottagare"
reference_number = "Referensnummer"
to_pay = "Att betala"
