name: CI
on:
  push:
  workflow_dispatch:

jobs:
  lint-format:
    name: Lint and format
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Cache Rust dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install Just
        uses: baptiste0928/cargo-install@v3
        with:
          crate: just
        
      - name: Install Rust tools
        run: just install-dev-deps
        
      - name: Install Typstyle
        uses: baptiste0928/cargo-install@v3
        with:
          crate: typstyle
        
      - name: Lint
        run: just lint-fix
      
      - name: Format
        run: just format

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions[bot]
          author_email: github-ations[bot]@users.noreply.github.com
          message: "Format"


  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Cache Rust dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Add WASM target
        run: rustup target add wasm32-unknown-unknown

      - name: Install Just
        uses: baptiste0928/cargo-install@v3
        with:
          crate: just

      - name: Install Tytanic
        uses: baptiste0928/cargo-install@v3
        with:
          crate: tytanic

      - name: Build
        run: just build

      - name: Run tests
        run: just test

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Cache Rust dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Add WASM target
        run: rustup target add wasm32-unknown-unknown

      - name: Install Just
        uses: baptiste0928/cargo-install@v3
        with:
          crate: just

      - name: Build WASM plugin
        run: just build

      - name: Setup Typst
        uses: typst-community/setup-typst@v4

      - name: Build
        run: typst compile template/main.typ --root .