name: CI
on:
  push:
  workflow_dispatch:

jobs:
  lint-format:
    name: Lint and format
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Install Just
        uses: baptiste0928/cargo-install@v3
        with:
          crate: just
        
      - name: Install Rust tools
        run: just install-dev-deps

      - name: Lint
        run: just lint-fix
      
      - name: Format
        run: just format

      - name: Install Typstyle
        uses: baptiste0928/cargo-install@v3
        with:
          crate: typstyle

      - name: Format
        run: typstyle -i .

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions[bot]
          author_email: github-ations[bot]@users.noreply.github.com
          message: "Format"

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Typst
        uses: typst-community/setup-typst@v4

      - name: Build
        run: typst compile template/main.typ --root .