[package]
name = "rust-tools"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
ciborium = "0.2.2"
rust_decimal = "1.37.2"
serde = "1.0.219"
wasm-minimal-protocol = "0.1.0"

[profile.release]
lto = true
strip = true
opt-level = 'z'
codegen-units = 1
panic = 'abort'
